"""Added aggregate and relationship  methods

Revision ID: 62f15c742779
Revises: 41d7bcabdaa8
Create Date: 2023-12-09 22:39:57.391191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f15c742779'
down_revision: Union[str, None] = '41d7bcabdaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
